<?php
/*
* This file has been automatically generated by Mouf/ORM.
* DO NOT edit this file, as it might be overwritten.
* If you need to perform changes, edit the OauthRefreshTokenDao class instead!
*/
namespace Mouf\OauthServer\Model\DAOs;

use Mouf\Database\DAOInterface;
use Mouf\Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Mouf\OauthServer\Model\Entities\OauthRefreshToken;

/**
* The OauthRefreshTokenBaseDao class will maintain the persistance of OauthRefreshToken class into the oauth_refresh_tokens table.
*
*/
class OauthRefreshTokenBaseDao extends EntityRepository implements DAOInterface {

	/**
	 * @param EntityManager $entityManager
	 */
	public function __construct($entityManager){
		parent::__construct($entityManager, $entityManager->getClassMetadata('Mouf\OauthServer\Model\Entities\OauthRefreshToken'));
	}


	/**
	 * Get a new bean record
	 * * @return OauthRefreshToken the new bean object
	 */
	public function create(){
		return new OauthRefreshToken();
	}

	/**
	 * Get a bean by it's Id
	 * @param mixed $id
	 * @return OauthRefreshToken the bean object
	 */
	public function getById($id){
		return $this->find($id);
	}

	/**
	 *
	 * Peforms saving on a bean object
	 * @param mixed bean object
	 */
	public function save($entity){
		$this->getEntityManager()->persist($entity);
	}

	/**
	 * Returns the lis of beans
	 * @return array[OauthRefreshToken] array of bean objects
	 */
	public function getList(){
		return $this->findAll();
	}

	/**
     * Finds only one entity. The criteria must contain all the elements needed to find a unique entity.
     * Throw an exception if more than one entity was found.
     *
     * @param array $criteria
     *
     * @return OauthRefreshToken the bean object
     */
    public function findUniqueBy(array $criteria)
    {
        $result = $this->findBy($criteria);

        if(count($result) == 1){
            return $result[0];
        }elseif(count($result) > 1){
            throw new NonUniqueResultException('More than one OauthRefreshToken was found');
        }else{
           return null;
        }
    }

	
	/**
	 * Wrapper around the magic __call implementations of the findBy[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @param int|null $limit the max elements to be returned
	 * @param int|null $offset the index of the first element to retrieve
	 * @return OauthRefreshToken[]
	 */
	public function findByExpireToken($fieldValue, $orderBy = null, $limit = null, $offset = null) {
		return $this->findBy(array('expire_token' => $fieldValue), $orderBy, $limit, $offset);
	}

	/**
	 * Wrapper around the magic __call implementations of the findByOne[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @return OauthRefreshToken
	 */
	public function findOneByExpireToken($fieldValue, $orderBy = null) {
		return $this->findOneBy(array('expire_token' => $fieldValue), $orderBy);
	}

	/**
	 * Finds only one entity by ExpireToken.
     * Throw an exception if more than one entity was found.
	 * @param mixed $fieldValue the value of the filtered field
	 * @return OauthRefreshToken
	 */
	public function findUniqueByExpireToken($fieldValue) {
		return $this->findUniqueBy(array('expire_token' => $fieldValue));
	}
}