<?php
/*
* This file has been automatically generated by Mouf/ORM.
* DO NOT edit this file, as it might be overwritten.
* If you need to perform changes, edit the OauthAuthCodeDao class instead!
*/
namespace Mouf\OauthServer\Model\DAOs;

use Mouf\Database\DAOInterface;
use Mouf\Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Mouf\OauthServer\Model\Entities\OauthAuthCode;

/**
* The OauthAuthCodeBaseDao class will maintain the persistance of OauthAuthCode class into the oauth_auth_codes table.
*
*/
class OauthAuthCodeBaseDao extends EntityRepository implements DAOInterface {

	/**
	 * @param EntityManager $entityManager
	 */
	public function __construct($entityManager){
		parent::__construct($entityManager, $entityManager->getClassMetadata('Mouf\OauthServer\Model\Entities\OauthAuthCode'));
	}


	/**
	 * Get a new bean record
	 * * @return OauthAuthCode the new bean object
	 */
	public function create(){
		return new OauthAuthCode();
	}

	/**
	 * Get a bean by it's Id
	 * @param mixed $id
	 * @return OauthAuthCode the bean object
	 */
	public function getById($id){
		return $this->find($id);
	}

	/**
	 *
	 * Peforms saving on a bean object
	 * @param mixed bean object
	 */
	public function save($entity){
		$this->getEntityManager()->persist($entity);
	}

	/**
	 * Returns the lis of beans
	 * @return array[OauthAuthCode] array of bean objects
	 */
	public function getList(){
		return $this->findAll();
	}

	/**
     * Finds only one entity. The criteria must contain all the elements needed to find a unique entity.
     * Throw an exception if more than one entity was found.
     *
     * @param array $criteria
     *
     * @return OauthAuthCode the bean object
     */
    public function findUniqueBy(array $criteria)
    {
        $result = $this->findBy($criteria);

        if(count($result) == 1){
            return $result[0];
        }elseif(count($result) > 1){
            throw new NonUniqueResultException('More than one OauthAuthCode was found');
        }else{
           return null;
        }
    }

	
	/**
	 * Wrapper around the magic __call implementations of the findBy[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @param int|null $limit the max elements to be returned
	 * @param int|null $offset the index of the first element to retrieve
	 * @return OauthAuthCode[]
	 */
	public function findByExpireTime($fieldValue, $orderBy = null, $limit = null, $offset = null) {
		return $this->findBy(array('expire_time' => $fieldValue), $orderBy, $limit, $offset);
	}

	/**
	 * Wrapper around the magic __call implementations of the findByOne[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @return OauthAuthCode
	 */
	public function findOneByExpireTime($fieldValue, $orderBy = null) {
		return $this->findOneBy(array('expire_time' => $fieldValue), $orderBy);
	}

	/**
	 * Finds only one entity by ExpireTime.
     * Throw an exception if more than one entity was found.
	 * @param mixed $fieldValue the value of the filtered field
	 * @return OauthAuthCode
	 */
	public function findUniqueByExpireTime($fieldValue) {
		return $this->findUniqueBy(array('expire_time' => $fieldValue));
	}
	/**
	 * Wrapper around the magic __call implementations of the findBy[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @param int|null $limit the max elements to be returned
	 * @param int|null $offset the index of the first element to retrieve
	 * @return OauthAuthCode[]
	 */
	public function findByClientRedirectUri($fieldValue, $orderBy = null, $limit = null, $offset = null) {
		return $this->findBy(array('client_redirect_uri' => $fieldValue), $orderBy, $limit, $offset);
	}

	/**
	 * Wrapper around the magic __call implementations of the findByOne[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @return OauthAuthCode
	 */
	public function findOneByClientRedirectUri($fieldValue, $orderBy = null) {
		return $this->findOneBy(array('client_redirect_uri' => $fieldValue), $orderBy);
	}

	/**
	 * Finds only one entity by ClientRedirectUri.
     * Throw an exception if more than one entity was found.
	 * @param mixed $fieldValue the value of the filtered field
	 * @return OauthAuthCode
	 */
	public function findUniqueByClientRedirectUri($fieldValue) {
		return $this->findUniqueBy(array('client_redirect_uri' => $fieldValue));
	}
}