<?php
/*
* This file has been automatically generated by Mouf/ORM.
* DO NOT edit this file, as it might be overwritten.
* If you need to perform changes, edit the OauthSessionDao class instead!
*/
namespace Mouf\OauthServer\Model\DAOs;

use Mouf\Database\DAOInterface;
use Mouf\Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Mouf\OauthServer\Model\Entities\OauthSession;

/**
* The OauthSessionBaseDao class will maintain the persistance of OauthSession class into the oauth_sessions table.
*
*/
class OauthSessionBaseDao extends EntityRepository implements DAOInterface {

	/**
	 * @param EntityManager $entityManager
	 */
	public function __construct($entityManager){
		parent::__construct($entityManager, $entityManager->getClassMetadata('Mouf\OauthServer\Model\Entities\OauthSession'));
	}


	/**
	 * Get a new bean record
	 * * @return OauthSession the new bean object
	 */
	public function create(){
		return new OauthSession();
	}

	/**
	 * Get a bean by it's Id
	 * @param mixed $id
	 * @return OauthSession the bean object
	 */
	public function getById($id){
		return $this->find($id);
	}

	/**
	 *
	 * Peforms saving on a bean object
	 * @param mixed bean object
	 */
	public function save($entity){
		$this->getEntityManager()->persist($entity);
	}

	/**
	 * Returns the lis of beans
	 * @return array[OauthSession] array of bean objects
	 */
	public function getList(){
		return $this->findAll();
	}

	/**
     * Finds only one entity. The criteria must contain all the elements needed to find a unique entity.
     * Throw an exception if more than one entity was found.
     *
     * @param array $criteria
     *
     * @return OauthSession the bean object
     */
    public function findUniqueBy(array $criteria)
    {
        $result = $this->findBy($criteria);

        if(count($result) == 1){
            return $result[0];
        }elseif(count($result) > 1){
            throw new NonUniqueResultException('More than one OauthSession was found');
        }else{
           return null;
        }
    }

	
	/**
	 * Wrapper around the magic __call implementations of the findBy[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @param int|null $limit the max elements to be returned
	 * @param int|null $offset the index of the first element to retrieve
	 * @return OauthSession[]
	 */
	public function findByOwnerType($fieldValue, $orderBy = null, $limit = null, $offset = null) {
		return $this->findBy(array('owner_type' => $fieldValue), $orderBy, $limit, $offset);
	}

	/**
	 * Wrapper around the magic __call implementations of the findByOne[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @return OauthSession
	 */
	public function findOneByOwnerType($fieldValue, $orderBy = null) {
		return $this->findOneBy(array('owner_type' => $fieldValue), $orderBy);
	}

	/**
	 * Finds only one entity by OwnerType.
     * Throw an exception if more than one entity was found.
	 * @param mixed $fieldValue the value of the filtered field
	 * @return OauthSession
	 */
	public function findUniqueByOwnerType($fieldValue) {
		return $this->findUniqueBy(array('owner_type' => $fieldValue));
	}
	/**
	 * Wrapper around the magic __call implementations of the findBy[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @param int|null $limit the max elements to be returned
	 * @param int|null $offset the index of the first element to retrieve
	 * @return OauthSession[]
	 */
	public function findByOwnerId($fieldValue, $orderBy = null, $limit = null, $offset = null) {
		return $this->findBy(array('owner_id' => $fieldValue), $orderBy, $limit, $offset);
	}

	/**
	 * Wrapper around the magic __call implementations of the findByOne[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @return OauthSession
	 */
	public function findOneByOwnerId($fieldValue, $orderBy = null) {
		return $this->findOneBy(array('owner_id' => $fieldValue), $orderBy);
	}

	/**
	 * Finds only one entity by OwnerId.
     * Throw an exception if more than one entity was found.
	 * @param mixed $fieldValue the value of the filtered field
	 * @return OauthSession
	 */
	public function findUniqueByOwnerId($fieldValue) {
		return $this->findUniqueBy(array('owner_id' => $fieldValue));
	}
	/**
	 * Wrapper around the magic __call implementations of the findBy[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @param int|null $limit the max elements to be returned
	 * @param int|null $offset the index of the first element to retrieve
	 * @return OauthSession[]
	 */
	public function findByClientRedirectUri($fieldValue, $orderBy = null, $limit = null, $offset = null) {
		return $this->findBy(array('client_redirect_uri' => $fieldValue), $orderBy, $limit, $offset);
	}

	/**
	 * Wrapper around the magic __call implementations of the findByOne[Field] function to get autocompletion
	 * @param mixed $fieldValue the value of the filtered field
	 * @param array|null $orderBy the value of the filtered field
	 * @return OauthSession
	 */
	public function findOneByClientRedirectUri($fieldValue, $orderBy = null) {
		return $this->findOneBy(array('client_redirect_uri' => $fieldValue), $orderBy);
	}

	/**
	 * Finds only one entity by ClientRedirectUri.
     * Throw an exception if more than one entity was found.
	 * @param mixed $fieldValue the value of the filtered field
	 * @return OauthSession
	 */
	public function findUniqueByClientRedirectUri($fieldValue) {
		return $this->findUniqueBy(array('client_redirect_uri' => $fieldValue));
	}
}